/*
 * This file is generated by jOOQ.
 */
package com.talentfront.jooq;


import com.talentfront.jooq.tables.Company;
import com.talentfront.jooq.tables.CompanyImage;
import com.talentfront.jooq.tables.CompanyLocation;
import com.talentfront.jooq.tables.Media;
import com.talentfront.jooq.tables.Notification;
import com.talentfront.jooq.tables.Posting;
import com.talentfront.jooq.tables.PostingRecommendation;
import com.talentfront.jooq.tables.PostingRequirement;
import com.talentfront.jooq.tables.User;
import com.talentfront.jooq.tables.UserCompany;
import com.talentfront.jooq.tables.UserEducation;
import com.talentfront.jooq.tables.UserExperience;
import com.talentfront.jooq.tables.UserImage;
import com.talentfront.jooq.tables.UserInfo;
import com.talentfront.jooq.tables.UserPostingApply;
import com.talentfront.jooq.tables.UserRelationship;
import com.talentfront.jooq.tables.UserReview;
import com.talentfront.jooq.tables.UserSession;
import com.talentfront.jooq.tables.UserSkill;
import com.talentfront.jooq.tables.UserType;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.2",
        "schema version:9.1"
    },
    date = "2021-05-08T20:05:20.887Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Db extends SchemaImpl {

    private static final long serialVersionUID = -1535287283;

    /**
     * The reference instance of <code>db</code>
     */
    public static final Db DB = new Db();

    /**
     * The table <code>db.company</code>.
     */
    public final Company COMPANY = Company.COMPANY;

    /**
     * The table <code>db.company_image</code>.
     */
    public final CompanyImage COMPANY_IMAGE = CompanyImage.COMPANY_IMAGE;

    /**
     * The table <code>db.company_location</code>.
     */
    public final CompanyLocation COMPANY_LOCATION = CompanyLocation.COMPANY_LOCATION;

    /**
     * The table <code>db.media</code>.
     */
    public final Media MEDIA = Media.MEDIA;

    /**
     * The table <code>db.notification</code>.
     */
    public final Notification NOTIFICATION = Notification.NOTIFICATION;

    /**
     * The table <code>db.posting</code>.
     */
    public final Posting POSTING = Posting.POSTING;

    /**
     * The table <code>db.posting_recommendation</code>.
     */
    public final PostingRecommendation POSTING_RECOMMENDATION = PostingRecommendation.POSTING_RECOMMENDATION;

    /**
     * The table <code>db.posting_requirement</code>.
     */
    public final PostingRequirement POSTING_REQUIREMENT = PostingRequirement.POSTING_REQUIREMENT;

    /**
     * The table <code>db.user</code>.
     */
    public final User USER = User.USER;

    /**
     * The table <code>db.user_company</code>.
     */
    public final UserCompany USER_COMPANY = UserCompany.USER_COMPANY;

    /**
     * The table <code>db.user_education</code>.
     */
    public final UserEducation USER_EDUCATION = UserEducation.USER_EDUCATION;

    /**
     * The table <code>db.user_experience</code>.
     */
    public final UserExperience USER_EXPERIENCE = UserExperience.USER_EXPERIENCE;

    /**
     * The table <code>db.user_image</code>.
     */
    public final UserImage USER_IMAGE = UserImage.USER_IMAGE;

    /**
     * The table <code>db.user_info</code>.
     */
    public final UserInfo USER_INFO = UserInfo.USER_INFO;

    /**
     * The table <code>db.user_posting_apply</code>.
     */
    public final UserPostingApply USER_POSTING_APPLY = UserPostingApply.USER_POSTING_APPLY;

    /**
     * The table <code>db.user_relationship</code>.
     */
    public final UserRelationship USER_RELATIONSHIP = UserRelationship.USER_RELATIONSHIP;

    /**
     * The table <code>db.user_review</code>.
     */
    public final UserReview USER_REVIEW = UserReview.USER_REVIEW;

    /**
     * The table <code>db.user_session</code>.
     */
    public final UserSession USER_SESSION = UserSession.USER_SESSION;

    /**
     * The table <code>db.user_skill</code>.
     */
    public final UserSkill USER_SKILL = UserSkill.USER_SKILL;

    /**
     * The table <code>db.user_type</code>.
     */
    public final UserType USER_TYPE = UserType.USER_TYPE;

    /**
     * No further instances allowed
     */
    private Db() {
        super("db", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Company.COMPANY,
            CompanyImage.COMPANY_IMAGE,
            CompanyLocation.COMPANY_LOCATION,
            Media.MEDIA,
            Notification.NOTIFICATION,
            Posting.POSTING,
            PostingRecommendation.POSTING_RECOMMENDATION,
            PostingRequirement.POSTING_REQUIREMENT,
            User.USER,
            UserCompany.USER_COMPANY,
            UserEducation.USER_EDUCATION,
            UserExperience.USER_EXPERIENCE,
            UserImage.USER_IMAGE,
            UserInfo.USER_INFO,
            UserPostingApply.USER_POSTING_APPLY,
            UserRelationship.USER_RELATIONSHIP,
            UserReview.USER_REVIEW,
            UserSession.USER_SESSION,
            UserSkill.USER_SKILL,
            UserType.USER_TYPE);
    }
}
