/*
 * This file is generated by jOOQ.
 */
package com.talentfront.jooq.tables.records;


import com.talentfront.jooq.tables.CompanyImage;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.2",
        "schema version:9.1"
    },
    date = "2021-05-08T20:05:20.887Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CompanyImageRecord extends UpdatableRecordImpl<CompanyImageRecord> implements Record6<Integer, Integer, String, byte[], String, LocalDateTime> {

    private static final long serialVersionUID = 1123837532;

    /**
     * Setter for <code>db.company_image.company_image_id</code>.
     */
    public void setCompanyImageId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>db.company_image.company_image_id</code>.
     */
    public Integer getCompanyImageId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>db.company_image.company_id</code>.
     */
    public void setCompanyId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>db.company_image.company_id</code>.
     */
    public Integer getCompanyId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>db.company_image.content_type</code>.
     */
    public void setContentType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>db.company_image.content_type</code>.
     */
    public String getContentType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>db.company_image.img</code>.
     */
    public void setImg(byte[] value) {
        set(3, value);
    }

    /**
     * Getter for <code>db.company_image.img</code>.
     */
    public byte[] getImg() {
        return (byte[]) get(3);
    }

    /**
     * Setter for <code>db.company_image.title</code>.
     */
    public void setTitle(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>db.company_image.title</code>.
     */
    public String getTitle() {
        return (String) get(4);
    }

    /**
     * Setter for <code>db.company_image.created_dt</code>.
     */
    public void setCreatedDt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>db.company_image.created_dt</code>.
     */
    public LocalDateTime getCreatedDt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, String, byte[], String, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Integer, String, byte[], String, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return CompanyImage.COMPANY_IMAGE.COMPANY_IMAGE_ID;
    }

    @Override
    public Field<Integer> field2() {
        return CompanyImage.COMPANY_IMAGE.COMPANY_ID;
    }

    @Override
    public Field<String> field3() {
        return CompanyImage.COMPANY_IMAGE.CONTENT_TYPE;
    }

    @Override
    public Field<byte[]> field4() {
        return CompanyImage.COMPANY_IMAGE.IMG;
    }

    @Override
    public Field<String> field5() {
        return CompanyImage.COMPANY_IMAGE.TITLE;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return CompanyImage.COMPANY_IMAGE.CREATED_DT;
    }

    @Override
    public Integer component1() {
        return getCompanyImageId();
    }

    @Override
    public Integer component2() {
        return getCompanyId();
    }

    @Override
    public String component3() {
        return getContentType();
    }

    @Override
    public byte[] component4() {
        return getImg();
    }

    @Override
    public String component5() {
        return getTitle();
    }

    @Override
    public LocalDateTime component6() {
        return getCreatedDt();
    }

    @Override
    public Integer value1() {
        return getCompanyImageId();
    }

    @Override
    public Integer value2() {
        return getCompanyId();
    }

    @Override
    public String value3() {
        return getContentType();
    }

    @Override
    public byte[] value4() {
        return getImg();
    }

    @Override
    public String value5() {
        return getTitle();
    }

    @Override
    public LocalDateTime value6() {
        return getCreatedDt();
    }

    @Override
    public CompanyImageRecord value1(Integer value) {
        setCompanyImageId(value);
        return this;
    }

    @Override
    public CompanyImageRecord value2(Integer value) {
        setCompanyId(value);
        return this;
    }

    @Override
    public CompanyImageRecord value3(String value) {
        setContentType(value);
        return this;
    }

    @Override
    public CompanyImageRecord value4(byte[] value) {
        setImg(value);
        return this;
    }

    @Override
    public CompanyImageRecord value5(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public CompanyImageRecord value6(LocalDateTime value) {
        setCreatedDt(value);
        return this;
    }

    @Override
    public CompanyImageRecord values(Integer value1, Integer value2, String value3, byte[] value4, String value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CompanyImageRecord
     */
    public CompanyImageRecord() {
        super(CompanyImage.COMPANY_IMAGE);
    }

    /**
     * Create a detached, initialised CompanyImageRecord
     */
    public CompanyImageRecord(Integer companyImageId, Integer companyId, String contentType, byte[] img, String title, LocalDateTime createdDt) {
        super(CompanyImage.COMPANY_IMAGE);

        set(0, companyImageId);
        set(1, companyId);
        set(2, contentType);
        set(3, img);
        set(4, title);
        set(5, createdDt);
    }
}
