/*
 * This file is generated by jOOQ.
 */
package com.talentfront.jooq.tables.records;


import com.talentfront.jooq.tables.Company;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.2",
        "schema version:9.1"
    },
    date = "2021-05-08T20:05:20.887Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CompanyRecord extends UpdatableRecordImpl<CompanyRecord> implements Record5<Integer, String, String, String, Integer> {

    private static final long serialVersionUID = 784914267;

    /**
     * Setter for <code>db.company.company_id</code>.
     */
    public void setCompanyId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>db.company.company_id</code>.
     */
    public Integer getCompanyId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>db.company.company_name</code>.
     */
    public void setCompanyName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>db.company.company_name</code>.
     */
    public String getCompanyName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>db.company.mission</code>.
     */
    public void setMission(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>db.company.mission</code>.
     */
    public String getMission() {
        return (String) get(2);
    }

    /**
     * Setter for <code>db.company.product</code>.
     */
    public void setProduct(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>db.company.product</code>.
     */
    public String getProduct() {
        return (String) get(3);
    }

    /**
     * Setter for <code>db.company.number_employees</code>.
     */
    public void setNumberEmployees(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>db.company.number_employees</code>.
     */
    public Integer getNumberEmployees() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, String, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, String, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Company.COMPANY.COMPANY_ID;
    }

    @Override
    public Field<String> field2() {
        return Company.COMPANY.COMPANY_NAME;
    }

    @Override
    public Field<String> field3() {
        return Company.COMPANY.MISSION;
    }

    @Override
    public Field<String> field4() {
        return Company.COMPANY.PRODUCT;
    }

    @Override
    public Field<Integer> field5() {
        return Company.COMPANY.NUMBER_EMPLOYEES;
    }

    @Override
    public Integer component1() {
        return getCompanyId();
    }

    @Override
    public String component2() {
        return getCompanyName();
    }

    @Override
    public String component3() {
        return getMission();
    }

    @Override
    public String component4() {
        return getProduct();
    }

    @Override
    public Integer component5() {
        return getNumberEmployees();
    }

    @Override
    public Integer value1() {
        return getCompanyId();
    }

    @Override
    public String value2() {
        return getCompanyName();
    }

    @Override
    public String value3() {
        return getMission();
    }

    @Override
    public String value4() {
        return getProduct();
    }

    @Override
    public Integer value5() {
        return getNumberEmployees();
    }

    @Override
    public CompanyRecord value1(Integer value) {
        setCompanyId(value);
        return this;
    }

    @Override
    public CompanyRecord value2(String value) {
        setCompanyName(value);
        return this;
    }

    @Override
    public CompanyRecord value3(String value) {
        setMission(value);
        return this;
    }

    @Override
    public CompanyRecord value4(String value) {
        setProduct(value);
        return this;
    }

    @Override
    public CompanyRecord value5(Integer value) {
        setNumberEmployees(value);
        return this;
    }

    @Override
    public CompanyRecord values(Integer value1, String value2, String value3, String value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CompanyRecord
     */
    public CompanyRecord() {
        super(Company.COMPANY);
    }

    /**
     * Create a detached, initialised CompanyRecord
     */
    public CompanyRecord(Integer companyId, String companyName, String mission, String product, Integer numberEmployees) {
        super(Company.COMPANY);

        set(0, companyId);
        set(1, companyName);
        set(2, mission);
        set(3, product);
        set(4, numberEmployees);
    }
}
