/*
 * This file is generated by jOOQ.
 */
package com.talentfront.jooq.tables.records;


import com.talentfront.jooq.tables.Notification;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.2",
        "schema version:9.1"
    },
    date = "2021-05-08T19:27:48.680Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationRecord extends UpdatableRecordImpl<NotificationRecord> implements Record5<Integer, Integer, Integer, String, String> {

    private static final long serialVersionUID = -1500673746;

    /**
     * Setter for <code>db.notification.notification_id</code>.
     */
    public void setNotificationId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>db.notification.notification_id</code>.
     */
    public Integer getNotificationId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>db.notification.sender_id</code>.
     */
    public void setSenderId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>db.notification.sender_id</code>.
     */
    public Integer getSenderId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>db.notification.reciever_id</code>.
     */
    public void setRecieverId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>db.notification.reciever_id</code>.
     */
    public Integer getRecieverId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>db.notification.data</code>.
     */
    public void setData(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>db.notification.data</code>.
     */
    public String getData() {
        return (String) get(3);
    }

    /**
     * Setter for <code>db.notification.status</code>.
     */
    public void setStatus(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>db.notification.status</code>.
     */
    public String getStatus() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, Integer, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, Integer, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Notification.NOTIFICATION.NOTIFICATION_ID;
    }

    @Override
    public Field<Integer> field2() {
        return Notification.NOTIFICATION.SENDER_ID;
    }

    @Override
    public Field<Integer> field3() {
        return Notification.NOTIFICATION.RECIEVER_ID;
    }

    @Override
    public Field<String> field4() {
        return Notification.NOTIFICATION.DATA;
    }

    @Override
    public Field<String> field5() {
        return Notification.NOTIFICATION.STATUS;
    }

    @Override
    public Integer component1() {
        return getNotificationId();
    }

    @Override
    public Integer component2() {
        return getSenderId();
    }

    @Override
    public Integer component3() {
        return getRecieverId();
    }

    @Override
    public String component4() {
        return getData();
    }

    @Override
    public String component5() {
        return getStatus();
    }

    @Override
    public Integer value1() {
        return getNotificationId();
    }

    @Override
    public Integer value2() {
        return getSenderId();
    }

    @Override
    public Integer value3() {
        return getRecieverId();
    }

    @Override
    public String value4() {
        return getData();
    }

    @Override
    public String value5() {
        return getStatus();
    }

    @Override
    public NotificationRecord value1(Integer value) {
        setNotificationId(value);
        return this;
    }

    @Override
    public NotificationRecord value2(Integer value) {
        setSenderId(value);
        return this;
    }

    @Override
    public NotificationRecord value3(Integer value) {
        setRecieverId(value);
        return this;
    }

    @Override
    public NotificationRecord value4(String value) {
        setData(value);
        return this;
    }

    @Override
    public NotificationRecord value5(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public NotificationRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NotificationRecord
     */
    public NotificationRecord() {
        super(Notification.NOTIFICATION);
    }

    /**
     * Create a detached, initialised NotificationRecord
     */
    public NotificationRecord(Integer notificationId, Integer senderId, Integer recieverId, String data, String status) {
        super(Notification.NOTIFICATION);

        set(0, notificationId);
        set(1, senderId);
        set(2, recieverId);
        set(3, data);
        set(4, status);
    }
}
