/*
 * This file is generated by jOOQ.
 */
package com.talentfront.jooq.tables.records;


import com.talentfront.jooq.tables.PostingRecommendation;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.2",
        "schema version:5.1"
    },
    date = "2021-04-11T05:11:40.089Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostingRecommendationRecord extends UpdatableRecordImpl<PostingRecommendationRecord> implements Record6<Integer, Integer, Integer, Integer, String, LocalDateTime> {

    private static final long serialVersionUID = 432056598;

    /**
     * Setter for <code>db.posting_recommendation.posting_recommendation_id</code>.
     */
    public void setPostingRecommendationId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>db.posting_recommendation.posting_recommendation_id</code>.
     */
    public Integer getPostingRecommendationId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>db.posting_recommendation.recommender_id</code>.
     */
    public void setRecommenderId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>db.posting_recommendation.recommender_id</code>.
     */
    public Integer getRecommenderId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>db.posting_recommendation.recommendee_id</code>.
     */
    public void setRecommendeeId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>db.posting_recommendation.recommendee_id</code>.
     */
    public Integer getRecommendeeId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>db.posting_recommendation.posting_id</code>.
     */
    public void setPostingId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>db.posting_recommendation.posting_id</code>.
     */
    public Integer getPostingId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>db.posting_recommendation.text</code>.
     */
    public void setText(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>db.posting_recommendation.text</code>.
     */
    public String getText() {
        return (String) get(4);
    }

    /**
     * Setter for <code>db.posting_recommendation.created_dt</code>.
     */
    public void setCreatedDt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>db.posting_recommendation.created_dt</code>.
     */
    public LocalDateTime getCreatedDt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, Integer, Integer, String, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Integer, Integer, Integer, String, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return PostingRecommendation.POSTING_RECOMMENDATION.POSTING_RECOMMENDATION_ID;
    }

    @Override
    public Field<Integer> field2() {
        return PostingRecommendation.POSTING_RECOMMENDATION.RECOMMENDER_ID;
    }

    @Override
    public Field<Integer> field3() {
        return PostingRecommendation.POSTING_RECOMMENDATION.RECOMMENDEE_ID;
    }

    @Override
    public Field<Integer> field4() {
        return PostingRecommendation.POSTING_RECOMMENDATION.POSTING_ID;
    }

    @Override
    public Field<String> field5() {
        return PostingRecommendation.POSTING_RECOMMENDATION.TEXT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return PostingRecommendation.POSTING_RECOMMENDATION.CREATED_DT;
    }

    @Override
    public Integer component1() {
        return getPostingRecommendationId();
    }

    @Override
    public Integer component2() {
        return getRecommenderId();
    }

    @Override
    public Integer component3() {
        return getRecommendeeId();
    }

    @Override
    public Integer component4() {
        return getPostingId();
    }

    @Override
    public String component5() {
        return getText();
    }

    @Override
    public LocalDateTime component6() {
        return getCreatedDt();
    }

    @Override
    public Integer value1() {
        return getPostingRecommendationId();
    }

    @Override
    public Integer value2() {
        return getRecommenderId();
    }

    @Override
    public Integer value3() {
        return getRecommendeeId();
    }

    @Override
    public Integer value4() {
        return getPostingId();
    }

    @Override
    public String value5() {
        return getText();
    }

    @Override
    public LocalDateTime value6() {
        return getCreatedDt();
    }

    @Override
    public PostingRecommendationRecord value1(Integer value) {
        setPostingRecommendationId(value);
        return this;
    }

    @Override
    public PostingRecommendationRecord value2(Integer value) {
        setRecommenderId(value);
        return this;
    }

    @Override
    public PostingRecommendationRecord value3(Integer value) {
        setRecommendeeId(value);
        return this;
    }

    @Override
    public PostingRecommendationRecord value4(Integer value) {
        setPostingId(value);
        return this;
    }

    @Override
    public PostingRecommendationRecord value5(String value) {
        setText(value);
        return this;
    }

    @Override
    public PostingRecommendationRecord value6(LocalDateTime value) {
        setCreatedDt(value);
        return this;
    }

    @Override
    public PostingRecommendationRecord values(Integer value1, Integer value2, Integer value3, Integer value4, String value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PostingRecommendationRecord
     */
    public PostingRecommendationRecord() {
        super(PostingRecommendation.POSTING_RECOMMENDATION);
    }

    /**
     * Create a detached, initialised PostingRecommendationRecord
     */
    public PostingRecommendationRecord(Integer postingRecommendationId, Integer recommenderId, Integer recommendeeId, Integer postingId, String text, LocalDateTime createdDt) {
        super(PostingRecommendation.POSTING_RECOMMENDATION);

        set(0, postingRecommendationId);
        set(1, recommenderId);
        set(2, recommendeeId);
        set(3, postingId);
        set(4, text);
        set(5, createdDt);
    }
}
