/*
 * This file is generated by jOOQ.
 */
package com.talentfront.jooq.tables.records;


import com.talentfront.jooq.tables.UserReview;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.2",
        "schema version:8.1"
    },
    date = "2021-04-12T08:11:55.614Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserReviewRecord extends UpdatableRecordImpl<UserReviewRecord> implements Record4<Integer, String, Integer, Integer> {

    private static final long serialVersionUID = -1399244619;

    /**
     * Setter for <code>db.user_review.user_review_id</code>.
     */
    public void setUserReviewId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>db.user_review.user_review_id</code>.
     */
    public Integer getUserReviewId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>db.user_review.review_data</code>.
     */
    public void setReviewData(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>db.user_review.review_data</code>.
     */
    public String getReviewData() {
        return (String) get(1);
    }

    /**
     * Setter for <code>db.user_review.reviewer_id</code>.
     */
    public void setReviewerId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>db.user_review.reviewer_id</code>.
     */
    public Integer getReviewerId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>db.user_review.reviewee_id</code>.
     */
    public void setRevieweeId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>db.user_review.reviewee_id</code>.
     */
    public Integer getRevieweeId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return UserReview.USER_REVIEW.USER_REVIEW_ID;
    }

    @Override
    public Field<String> field2() {
        return UserReview.USER_REVIEW.REVIEW_DATA;
    }

    @Override
    public Field<Integer> field3() {
        return UserReview.USER_REVIEW.REVIEWER_ID;
    }

    @Override
    public Field<Integer> field4() {
        return UserReview.USER_REVIEW.REVIEWEE_ID;
    }

    @Override
    public Integer component1() {
        return getUserReviewId();
    }

    @Override
    public String component2() {
        return getReviewData();
    }

    @Override
    public Integer component3() {
        return getReviewerId();
    }

    @Override
    public Integer component4() {
        return getRevieweeId();
    }

    @Override
    public Integer value1() {
        return getUserReviewId();
    }

    @Override
    public String value2() {
        return getReviewData();
    }

    @Override
    public Integer value3() {
        return getReviewerId();
    }

    @Override
    public Integer value4() {
        return getRevieweeId();
    }

    @Override
    public UserReviewRecord value1(Integer value) {
        setUserReviewId(value);
        return this;
    }

    @Override
    public UserReviewRecord value2(String value) {
        setReviewData(value);
        return this;
    }

    @Override
    public UserReviewRecord value3(Integer value) {
        setReviewerId(value);
        return this;
    }

    @Override
    public UserReviewRecord value4(Integer value) {
        setRevieweeId(value);
        return this;
    }

    @Override
    public UserReviewRecord values(Integer value1, String value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserReviewRecord
     */
    public UserReviewRecord() {
        super(UserReview.USER_REVIEW);
    }

    /**
     * Create a detached, initialised UserReviewRecord
     */
    public UserReviewRecord(Integer userReviewId, String reviewData, Integer reviewerId, Integer revieweeId) {
        super(UserReview.USER_REVIEW);

        set(0, userReviewId);
        set(1, reviewData);
        set(2, reviewerId);
        set(3, revieweeId);
    }
}
