/*
 * This file is generated by jOOQ.
 */
package com.talentfront.jooq.tables.records;


import com.talentfront.jooq.tables.UserExperience;

import java.time.LocalDate;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.2",
        "schema version:4.1"
    },
    date = "2021-04-05T05:33:17.278Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserExperienceRecord extends UpdatableRecordImpl<UserExperienceRecord> implements Record6<Integer, String, String, LocalDate, LocalDate, Integer> {

    private static final long serialVersionUID = 143118739;

    /**
     * Setter for <code>db.user_experience.user_exeperince_id</code>.
     */
    public void setUserExeperinceId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>db.user_experience.user_exeperince_id</code>.
     */
    public Integer getUserExeperinceId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>db.user_experience.job_title</code>.
     */
    public void setJobTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>db.user_experience.job_title</code>.
     */
    public String getJobTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>db.user_experience.experience</code>.
     */
    public void setExperience(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>db.user_experience.experience</code>.
     */
    public String getExperience() {
        return (String) get(2);
    }

    /**
     * Setter for <code>db.user_experience.date_start</code>.
     */
    public void setDateStart(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>db.user_experience.date_start</code>.
     */
    public LocalDate getDateStart() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>db.user_experience.date_end</code>.
     */
    public void setDateEnd(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>db.user_experience.date_end</code>.
     */
    public LocalDate getDateEnd() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>db.user_experience.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>db.user_experience.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, LocalDate, LocalDate, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, LocalDate, LocalDate, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return UserExperience.USER_EXPERIENCE.USER_EXEPERINCE_ID;
    }

    @Override
    public Field<String> field2() {
        return UserExperience.USER_EXPERIENCE.JOB_TITLE;
    }

    @Override
    public Field<String> field3() {
        return UserExperience.USER_EXPERIENCE.EXPERIENCE;
    }

    @Override
    public Field<LocalDate> field4() {
        return UserExperience.USER_EXPERIENCE.DATE_START;
    }

    @Override
    public Field<LocalDate> field5() {
        return UserExperience.USER_EXPERIENCE.DATE_END;
    }

    @Override
    public Field<Integer> field6() {
        return UserExperience.USER_EXPERIENCE.USER_ID;
    }

    @Override
    public Integer component1() {
        return getUserExeperinceId();
    }

    @Override
    public String component2() {
        return getJobTitle();
    }

    @Override
    public String component3() {
        return getExperience();
    }

    @Override
    public LocalDate component4() {
        return getDateStart();
    }

    @Override
    public LocalDate component5() {
        return getDateEnd();
    }

    @Override
    public Integer component6() {
        return getUserId();
    }

    @Override
    public Integer value1() {
        return getUserExeperinceId();
    }

    @Override
    public String value2() {
        return getJobTitle();
    }

    @Override
    public String value3() {
        return getExperience();
    }

    @Override
    public LocalDate value4() {
        return getDateStart();
    }

    @Override
    public LocalDate value5() {
        return getDateEnd();
    }

    @Override
    public Integer value6() {
        return getUserId();
    }

    @Override
    public UserExperienceRecord value1(Integer value) {
        setUserExeperinceId(value);
        return this;
    }

    @Override
    public UserExperienceRecord value2(String value) {
        setJobTitle(value);
        return this;
    }

    @Override
    public UserExperienceRecord value3(String value) {
        setExperience(value);
        return this;
    }

    @Override
    public UserExperienceRecord value4(LocalDate value) {
        setDateStart(value);
        return this;
    }

    @Override
    public UserExperienceRecord value5(LocalDate value) {
        setDateEnd(value);
        return this;
    }

    @Override
    public UserExperienceRecord value6(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserExperienceRecord values(Integer value1, String value2, String value3, LocalDate value4, LocalDate value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserExperienceRecord
     */
    public UserExperienceRecord() {
        super(UserExperience.USER_EXPERIENCE);
    }

    /**
     * Create a detached, initialised UserExperienceRecord
     */
    public UserExperienceRecord(Integer userExeperinceId, String jobTitle, String experience, LocalDate dateStart, LocalDate dateEnd, Integer userId) {
        super(UserExperience.USER_EXPERIENCE);

        set(0, userExeperinceId);
        set(1, jobTitle);
        set(2, experience);
        set(3, dateStart);
        set(4, dateEnd);
        set(5, userId);
    }
}
