/*
 * This file is generated by jOOQ.
 */
package com.talentfront.jooq.tables.records;


import com.talentfront.jooq.tables.UserImage;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.2",
        "schema version:4.1"
    },
    date = "2021-04-03T20:58:38.186Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserImageRecord extends UpdatableRecordImpl<UserImageRecord> implements Record5<Integer, Integer, byte[], String, LocalDateTime> {

    private static final long serialVersionUID = 2019242711;

    /**
     * Setter for <code>db.user_image.user_image_id</code>.
     */
    public void setUserImageId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>db.user_image.user_image_id</code>.
     */
    public Integer getUserImageId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>db.user_image.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>db.user_image.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>db.user_image.img</code>.
     */
    public void setImg(byte[] value) {
        set(2, value);
    }

    /**
     * Getter for <code>db.user_image.img</code>.
     */
    public byte[] getImg() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>db.user_image.title</code>.
     */
    public void setTitle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>db.user_image.title</code>.
     */
    public String getTitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>db.user_image.created_dt</code>.
     */
    public void setCreatedDt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>db.user_image.created_dt</code>.
     */
    public LocalDateTime getCreatedDt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, byte[], String, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, byte[], String, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return UserImage.USER_IMAGE.USER_IMAGE_ID;
    }

    @Override
    public Field<Integer> field2() {
        return UserImage.USER_IMAGE.USER_ID;
    }

    @Override
    public Field<byte[]> field3() {
        return UserImage.USER_IMAGE.IMG;
    }

    @Override
    public Field<String> field4() {
        return UserImage.USER_IMAGE.TITLE;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return UserImage.USER_IMAGE.CREATED_DT;
    }

    @Override
    public Integer component1() {
        return getUserImageId();
    }

    @Override
    public Integer component2() {
        return getUserId();
    }

    @Override
    public byte[] component3() {
        return getImg();
    }

    @Override
    public String component4() {
        return getTitle();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedDt();
    }

    @Override
    public Integer value1() {
        return getUserImageId();
    }

    @Override
    public Integer value2() {
        return getUserId();
    }

    @Override
    public byte[] value3() {
        return getImg();
    }

    @Override
    public String value4() {
        return getTitle();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedDt();
    }

    @Override
    public UserImageRecord value1(Integer value) {
        setUserImageId(value);
        return this;
    }

    @Override
    public UserImageRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserImageRecord value3(byte[] value) {
        setImg(value);
        return this;
    }

    @Override
    public UserImageRecord value4(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public UserImageRecord value5(LocalDateTime value) {
        setCreatedDt(value);
        return this;
    }

    @Override
    public UserImageRecord values(Integer value1, Integer value2, byte[] value3, String value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserImageRecord
     */
    public UserImageRecord() {
        super(UserImage.USER_IMAGE);
    }

    /**
     * Create a detached, initialised UserImageRecord
     */
    public UserImageRecord(Integer userImageId, Integer userId, byte[] img, String title, LocalDateTime createdDt) {
        super(UserImage.USER_IMAGE);

        set(0, userImageId);
        set(1, userId);
        set(2, img);
        set(3, title);
        set(4, createdDt);
    }
}
