version: "3.3"
services:

  # About react app
  about:
    image: pachecosf/about-app:latest
    container_name: about
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - reverse-proxy
    networks:
      - app-network
  # Nginx Service
  reverse-proxy:
    image: pachecosf/reverse-proxy:latest
    restart: always
    ports:
      - 80:80
    networks:
      - app-network
  # Mysql
  mysql-db:
    image: mysql:5.7 
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=be-service
      - MYSQL_PASSWORD=belphagor
      # Password for root access
      - MYSQL_ROOT_PASSWORD=belphagorRoot
      - MYSQL_ROOT_HOST=%
    ports:
      - 3306:3306
    volumes:
      - datavolume:/var/lib/mysql
  # Migration to get database set up
  migration:
    image: boxfuse/flyway:latest
    command: -url=jdbc:mysql://mysql-db:3306/db?verifyServerCertificate=false&useSSL=true -schemas=db -user=root -password=belphagorRoot migrate
    container_name: flyway_migration
    volumes:
      - ../sql:/flyway/sql
    depends_on: 
      - mysql-db

volumes:
  datavolume:

networks:
  app-network:
    driver: bridge