version: "3.3"
services:

  # About react app
  about:
    image: pachecosf/about-app:latest
    container_name: about
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - reverse-proxy
    networks:
      - app-network
  # Nginx Service
  reverse-proxy:
    image: pachecosf/reverse-proxy:latest
    restart: always
    ports:
      - 80:80
    networks:
      - app-network
  # Mysql
  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'be-service'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'belphagor'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'belphagorRoot'
    ports:
      - 3306:3306
    volumes:
      - datavolume:/var/lib/mysql

volumes:
  datavolume:

networks:
  app-network:
    driver: bridge