/*
 * This file is generated by jOOQ.
 */
package com.talentfront.jooq.tables;


import com.talentfront.jooq.Db;
import com.talentfront.jooq.Keys;
import com.talentfront.jooq.tables.records.UserCompanyRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.2",
        "schema version:8.1"
    },
    date = "2021-04-26T01:55:23.836Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserCompany extends TableImpl<UserCompanyRecord> {

    private static final long serialVersionUID = -1242818582;

    /**
     * The reference instance of <code>db.user_company</code>
     */
    public static final UserCompany USER_COMPANY = new UserCompany();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserCompanyRecord> getRecordType() {
        return UserCompanyRecord.class;
    }

    /**
     * The column <code>db.user_company.user_company_id</code>.
     */
    public final TableField<UserCompanyRecord, Integer> USER_COMPANY_ID = createField(DSL.name("user_company_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>db.user_company.user_id</code>.
     */
    public final TableField<UserCompanyRecord, Integer> USER_ID = createField(DSL.name("user_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>db.user_company.company_name</code>.
     */
    public final TableField<UserCompanyRecord, String> COMPANY_NAME = createField(DSL.name("company_name"), org.jooq.impl.SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * Create a <code>db.user_company</code> table reference
     */
    public UserCompany() {
        this(DSL.name("user_company"), null);
    }

    /**
     * Create an aliased <code>db.user_company</code> table reference
     */
    public UserCompany(String alias) {
        this(DSL.name(alias), USER_COMPANY);
    }

    /**
     * Create an aliased <code>db.user_company</code> table reference
     */
    public UserCompany(Name alias) {
        this(alias, USER_COMPANY);
    }

    private UserCompany(Name alias, Table<UserCompanyRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserCompany(Name alias, Table<UserCompanyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> UserCompany(Table<O> child, ForeignKey<O, UserCompanyRecord> key) {
        super(child, key, USER_COMPANY);
    }

    @Override
    public Schema getSchema() {
        return Db.DB;
    }

    @Override
    public Identity<UserCompanyRecord, Integer> getIdentity() {
        return Keys.IDENTITY_USER_COMPANY;
    }

    @Override
    public UniqueKey<UserCompanyRecord> getPrimaryKey() {
        return Keys.KEY_USER_COMPANY_PRIMARY;
    }

    @Override
    public List<UniqueKey<UserCompanyRecord>> getKeys() {
        return Arrays.<UniqueKey<UserCompanyRecord>>asList(Keys.KEY_USER_COMPANY_PRIMARY);
    }

    @Override
    public List<ForeignKey<UserCompanyRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<UserCompanyRecord, ?>>asList(Keys.USER_COMPANY_USER_ID_FK);
    }

    public User user() {
        return new User(this, Keys.USER_COMPANY_USER_ID_FK);
    }

    @Override
    public UserCompany as(String alias) {
        return new UserCompany(DSL.name(alias), this);
    }

    @Override
    public UserCompany as(Name alias) {
        return new UserCompany(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserCompany rename(String name) {
        return new UserCompany(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserCompany rename(Name name) {
        return new UserCompany(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
