name: Publish Reverse Proxy

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Push About
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: pachecosf/about-app:latest
        context: .
        file: ./application/fe/about-app/Dockerfile
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}